apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: auth-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth-app-deployment
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 85
