apiVersion: v1
kind: Service
metadata:
  name: auth-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80        # porta externa (LB)
      targetPort: 3333 # porta no container/pod
      protocol: TCP
  selector:
    app: auth-app
